name: fractional_progress_stepper
description: "Directly conveys support for fractional (non-integer) steps."
version: 0.0.1

homepage: https://github.com/pritom-shajed
repository: https://github.com/pritom-shajed/fractional_progress_stepper.git
issue_tracker: https://github.com/pritom-shajed/fractional_progress_stepper/issues

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0